title: Kevin Proudler # your name (or website title) here
logo: "/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Enthusiast 
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/kevinproudler/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-T9BB4R6T2T # your Google Analytics tracking ID here
